- hosts: my_vm
  become: yes
  tasks:
    - name: Pull MySQL Docker image
      community.docker.docker_image:
        name: mysql
        tag: latest
        source: pull

    - name: Run MySQL container for Shazaib
      community.docker.docker_container:
        name: mysql-server-shazaib
        image: mysql:latest
        state: started
        env:
          MYSQL_ROOT_PASSWORD: "shazaib_root_password"
          MYSQL_DATABASE: "shazaib_zabbix"
          MYSQL_USER: "shazaib_zabbix"
          MYSQL_PASSWORD: "shazaib_zabbix"
        ports:
          - "3318:3306"

    - name: Pull Zabbix Docker image
      community.docker.docker_image:
        name: zabbix/zabbix-server-mysql
        tag: latest
        source: pull

    - name: Run Zabbix container for Shazaib
      community.docker.docker_container:
        name: zabbix-shazaib
        image: zabbix/zabbix-server-mysql:latest
        state: started
        ports:
          - "8099:80"
          - "10064:10051"
        env:
          DB_SERVER_HOST: "mysql-server-shazaib"
          MYSQL_USER: "shazaib_zabbix"
          MYSQL_PASSWORD: "shazaib_zabbix"
          MYSQL_DATABASE: "shazaib_zabbix"

    - name: Pull Nagios Docker image
      community.docker.docker_image:
        name: jasonrivers/nagios
        tag: latest
        source: pull

    - name: Run Nagios container for Shazaib
      community.docker.docker_container:
        name: nagios-shazaib
        image: jasonrivers/nagios:latest
        state: started
        ports:
          - "8100:80"

    - name: Pull Prometheus Docker image
      community.docker.docker_image:
        name: prom/prometheus
        tag: v2.30.3
        source: pull

    - name: Run Prometheus container for Shazaib
      community.docker.docker_container:
        name: prometheus-shazaib
        image: prom/prometheus:v2.30.3
        state: started
        ports:
          - "8101:9090"